# flake8: noqa

"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: v1alpha
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from furiosa.client.api_client import ApiClient

# import Configuration
from furiosa.client.configuration import Configuration

# import exceptions
from furiosa.client.exceptions import OpenApiException
from furiosa.client.exceptions import ApiAttributeError
from furiosa.client.exceptions import ApiTypeError
from furiosa.client.exceptions import ApiValueError
from furiosa.client.exceptions import ApiKeyError
from furiosa.client.exceptions import ApiException
