"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: v1alpha
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import furiosa.openapi
from furiosa.openapi.model.compile_status_status import CompileStatusStatus


class TestCompileStatusStatus(unittest.TestCase):
    """CompileStatusStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompileStatusStatus(self):
        """Test CompileStatusStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompileStatusStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
