"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: v1alpha
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import furiosa.openapi
from furiosa.openapi.model.compile_status import CompileStatus
globals()['CompileStatus'] = CompileStatus
from furiosa.openapi.model.compile_status_list import CompileStatusList


class TestCompileStatusList(unittest.TestCase):
    """CompileStatusList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompileStatusList(self):
        """Test CompileStatusList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompileStatusList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
