"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: v1alpha
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import furiosa.client
from furiosa.client.model.compile_output import CompileOutput


class TestCompileOutput(unittest.TestCase):
    """CompileOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompileOutput(self):
        """Test CompileOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompileOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
