"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: v1alpha
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import unittest

import furiosa.client
from furiosa.client.api.compiler_v1_api import CompilerV1Api  # noqa: E501


class TestCompilerV1Api(unittest.TestCase):
    """CompilerV1Api unit test stubs"""

    def setUp(self):
        self.api = CompilerV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_compile(self):
        """Test case for compile

        Compile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
