"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import unittest

import client
from client.api.compiler_api import CompilerApi  # noqa: E501


class TestCompilerApi(unittest.TestCase):
    """CompilerApi unit test stubs"""

    def setUp(self):
        self.api = CompilerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_compile(self):
        """Test case for compile

        Compile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
