"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import unittest

import client
from client.api.account_api import AccountApi  # noqa: E501


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_api_key(self):
        """Test case for create_api_key

        Generate new API key  # noqa: E501
        """
        pass

    def test_delete_api_key(self):
        """Test case for delete_api_key

        Delete a API key  # noqa: E501
        """
        pass

    def test_get_account_info(self):
        """Test case for get_account_info

        Get my account information  # noqa: E501
        """
        pass

    def test_get_api_key(self):
        """Test case for get_api_key

        Get a API key  # noqa: E501
        """
        pass

    def test_list_api_keys(self):
        """Test case for list_api_keys

        List generated API keys  # noqa: E501
        """
        pass

    def test_update_account_info(self):
        """Test case for update_account_info

        Update my account information  # noqa: E501
        """
        pass

    def test_update_account_password(self):
        """Test case for update_account_password

        Change my account password  # noqa: E501
        """
        pass

    def test_update_api_key(self):
        """Test case for update_api_key

        Update a API key  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
