"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import unittest

import client
from client.api.perfeye_api import PerfeyeApi  # noqa: E501


class TestPerfeyeApi(unittest.TestCase):
    """PerfeyeApi unit test stubs"""

    def setUp(self):
        self.api = PerfeyeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_perfeye_post(self):
        """Test case for perfeye_post

        Generate a visualized performance estimation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
