"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: v1alpha
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import furiosa.client
from furiosa.client.model.api_key_patch_request import ApiKeyPatchRequest


class TestApiKeyPatchRequest(unittest.TestCase):
    """ApiKeyPatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiKeyPatchRequest(self):
        """Test ApiKeyPatchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiKeyPatchRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
