"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import furiosa.client
from furiosa.client.model.api_key_request import ApiKeyRequest


class TestApiKeyRequest(unittest.TestCase):
    """ApiKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiKeyRequest(self):
        """Test ApiKeyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiKeyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
