"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import client
from client.model.login_response import LoginResponse


class TestLoginResponse(unittest.TestCase):
    """LoginResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginResponse(self):
        """Test LoginResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
