"""
    Furiosa AI Web Service API

    Furiosa AI Web Service API for Compiler and Model Tools  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: contact@furisa.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import client
from client.model.masked_api_key import MaskedApiKey


class TestMaskedApiKey(unittest.TestCase):
    """MaskedApiKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMaskedApiKey(self):
        """Test MaskedApiKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MaskedApiKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
